config/routes.rb
Rails.application.routes.draw do
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/home', to: 'static_pages#home'
  get '/home/:user_name', to: 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :marks
  has_many :tags, through: :marks
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :marks
  has_many :gossips, through: :gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage", dependent: :destroy
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def home
    @allgossips = Gossip.all
    @id = params[:user_name]
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>NewGossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h1>TheGossipProject</h1>
  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", home_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>You can contact us here : '+44 1632 960990'</p>

app/views/static_pages/home.html.erb
<html>
  <body>
    <h2>Welcome to The Gossip Project <%= @id %> !</h2>
    <p>Scroll and see all the gathered gossips so far below : </p>
    <% @allgossips.each do |gossip| %>
      <p>
      <%= gossip.title %><br/>
      <%= gossip.content %><br/>
      <%= gossip.user.first_name %>
      </p>
    <% end %> 
  </body>
</html>    

app/views/static_pages/team.html.erb
<h1>Team</h1>
<p>Our lovely team : FRANKIM (Franky & Kim)</p>